In [4]:
import pandas as pd

In [5]:
data_2018 = pd.read_csv("2018.csv") 
data_2017 = pd.read_csv("2017.csv") 
data_2016 = pd.read_csv("2016.csv")

In [6]:
columns_2018=data_2018.columns
columns_2017=data_2017.columns
columns_2016=data_2016.columns

In [7]:
columns_2018==columns_2017

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [8]:
columns_2018==columns_2016

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [9]:
columns_2018

Index(['FL_DATE', 'OP_CARRIER', 'OP_CARRIER_FL_NUM', 'ORIGIN', 'DEST',
       'CRS_DEP_TIME', 'DEP_TIME', 'DEP_DELAY', 'TAXI_OUT', 'WHEELS_OFF',
       'WHEELS_ON', 'TAXI_IN', 'CRS_ARR_TIME', 'ARR_TIME', 'ARR_DELAY',
       'CANCELLED', 'CANCELLATION_CODE', 'DIVERTED', 'CRS_ELAPSED_TIME',
       'ACTUAL_ELAPSED_TIME', 'AIR_TIME', 'DISTANCE', 'CARRIER_DELAY',
       'WEATHER_DELAY', 'NAS_DELAY', 'SECURITY_DELAY', 'LATE_AIRCRAFT_DELAY',
       'Unnamed: 27'],
      dtype='object')

In [10]:
data_2016.count()[0]
data_2017.count()[0]
data_2018.count()[0]

7213446

In [27]:
file_2018_path = r"C:\Users\anne_\OneDrive\Documents\GitHub\Final-Project\Resources\2018.csv"

In [28]:
data_2018_df = pd.read_csv(file_2018_path,encoding="utf-8")
data_2018_df.head(10)

,FL_DATE,OP_CARRIER,OP_CARRIER_FL_NUM,ORIGIN,DEST,CRS_DEP_TIME,DEP_TIME,DEP_DELAY,TAXI_OUT,WHEELS_OFF,...,CRS_ELAPSED_TIME,ACTUAL_ELAPSED_TIME,AIR_TIME,DISTANCE,CARRIER_DELAY,WEATHER_DELAY,NAS_DELAY,SECURITY_DELAY,LATE_AIRCRAFT_DELAY,Unnamed: 27
0,2018-01-01,UA,2429,EWR,DEN,1517,1512.0,-5.0,15.0,1527.0,...,268.0,250.0,225.0,1605.0,NaN,NaN,NaN,NaN,NaN,NaN
1,2018-01-01,UA,2427,LAS,SFO,1115,1107.0,-8.0,11.0,1118.0,...,99.0,83.0,65.0,414.0,NaN,NaN,NaN,NaN,NaN,NaN
2,2018-01-01,UA,2426,SNA,DEN,1335,1330.0,-5.0,15.0,1345.0,...,134.0,126.0,106.0,846.0,NaN,NaN,NaN,NaN,NaN,NaN
3,2018-01-01,UA,2425,RSW,ORD,1546,1552.0,6.0,19.0,1611.0,...,190.0,182.0,157.0,1120.0,NaN,NaN,NaN,NaN,NaN,NaN
4,2018-01-01,UA,2424,ORD,ALB,630,650.0,20.0,13.0,703.0,...,112.0,106.0,83.0,723.0,NaN,NaN,NaN,NaN,NaN,NaN
5,2018-01-01,UA,2422,ORD,OMA,2241,2244.0,3.0,15.0,2259.0,...,93.0,79.0,62.0,416.0,NaN,NaN,NaN,NaN,NaN,NaN
6,2018-01-01,UA,2421,IAH,LAS,750,747.0,-3.0,14.0,801.0,...,206.0,193.0,173.0,1222.0,NaN,NaN,NaN,NaN,NaN,NaN
7,2018-01-01,UA,2420,DEN,CID,1324,1318.0,-6.0,11.0,1329.0,...,115.0,102.0,85.0,692.0,NaN,NaN,NaN,NaN,NaN,NaN
8,2018-01-01,UA,2419,SMF,EWR,2224,2237.0,13.0,10.0,2247.0,...,314.0,299.0,280.0,2500.0,NaN,NaN,NaN,NaN,NaN,NaN
9,2018-01-01,UA,2418,RIC,DEN,1601,1559.0,-2.0,12.0,1611.0,...,252.0,237.0,217.0,1482.0,NaN,NaN,NaN,NaN,NaN,NaN

In [35]:
data_2018_df.loc[data_2018_df['ORIGIN'] == "PHX"]

,FL_DATE,OP_CARRIER,OP_CARRIER_FL_NUM,ORIGIN,DEST,CRS_DEP_TIME,DEP_TIME,DEP_DELAY,TAXI_OUT,WHEELS_OFF,...,CRS_ELAPSED_TIME,ACTUAL_ELAPSED_TIME,AIR_TIME,DISTANCE,CARRIER_DELAY,WEATHER_DELAY,NAS_DELAY,SECURITY_DELAY,LATE_AIRCRAFT_DELAY,Unnamed: 27
81,2018-01-01,UA,2135,PHX,DEN,1435,1424.0,-11.0,11.0,1435.0,...,106.0,93.0,78.0,602.0,NaN,NaN,NaN,NaN,NaN,NaN
134,2018-01-01,UA,2083,PHX,IAH,730,729.0,-1.0,10.0,739.0,...,152.0,135.0,121.0,1009.0,NaN,NaN,NaN,NaN,NaN,NaN
207,2018-01-01,UA,2000,PHX,ORD,1340,1328.0,-12.0,13.0,1341.0,...,205.0,193.0,177.0,1440.0,NaN,NaN,NaN,NaN,NaN,NaN
235,2018-01-01,UA,1976,PHX,EWR,2330,2324.0,-6.0,10.0,2334.0,...,275.0,254.0,238.0,2133.0,NaN,NaN,NaN,NaN,NaN,NaN
415,2018-01-01,UA,1774,PHX,DEN,600,558.0,-2.0,10.0,608.0,...,107.0,94.0,79.0,602.0,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7213333,2018-12-31,AA,1702,PHX,LAX,937,940.0,3.0,22.0,1002.0,...,107.0,106.0,64.0,370.0,NaN,NaN,NaN,NaN,NaN,NaN
7213369,2018-12-31,AA,1743,PHX,DEN,1330,1326.0,-4.0,11.0,1337.0,...,107.0,106.0,76.0,602.0,NaN,NaN,NaN,NaN,NaN,NaN
7213382,2018-12-31,AA,1760,PHX,AUS,1328,1322.0,-6.0,10.0,1332.0,...,129.0,131.0,103.0,872.0,NaN,NaN,NaN,NaN,NaN,NaN
7213413,2018-12-31,AA,1792,PHX,CMH,955,953.0,-2.0,34.0,1027.0,...,222.0,221.0,178.0,1670.0,NaN,NaN,NaN,NaN,NaN,NaN
7213437,2018-12-31,AA,1812,PHX,PDX,825,821.0,-4.0,15.0,836.0,...,172.0,175.0,158.0,1009.0,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# Remove unecessary columns from the DataFrame and save the new DataFrame
# Only keep: "isbn", "original_publication_year", "original_title", "authors",
# "ratings_1", "ratings_2", "ratings_3", "ratings_4", "ratings_5"
reduced_2018_df = data_2018[['WHEELS_OFF', 'WHEELS_ON', 'CRS_ELAPSED_TIME',
      'AIR_TIME', 'DISTANCE']]
reduced_df.head()

NameError: name 'reduced_df' is not defined